include ../../docker.mk
include ../../help.mk
include ../../shell.mk

IMAGE_NAME=utils-zip

.PHONY: clean
clean: ## Clean up after the build process.

.PHONY: lint
lint: docker-lint ## Lint all of the files for this Action.

.PHONY: test
test: ## Test the components of this Action.

.PHONY: build
build: docker-build ## Build this Action.